### ISSUE TITLE
Title with special character causes a syntax error

### ISSUE THREAD

**Issue by arthur-proglove** [jacksmith15/statham-schema#77]
**Describe the bug**
A JSON schema with a special character in its title (non alphanumerical) causes the generated Python code to be incorrect.

**Steps to Reproduce**
Create a JSON schema with the following title:
`"My Test JSON Schema!"`

**Expected behaviour**
A class should be defined without the exclamation mark:
`class MyTestJSONSchema:`

**Actual behaviour**
The class is defined as is:
`class MyTestJSONSchema!:`

**Comment by arthur-proglove** [comment]
Sanitizing the title with something like `re.sub('[^a-zA-Z0-9_\s]', '_', name)` should do the trick ;-)

**Comment by jacksmith15** [comment]
Well spotted @arthur-proglove - and thanks for providing a clear example! :+1:

**Comment by arthur-proglove** [comment]
That was fast! :-D

**Comment by jacksmith15** [comment]
Fixed in 0.13.0 ([PyPI](https://pypi.org/project/statham-schema/0.13.0/), [GitHub](https://github.com/jacksmith15/statham-schema/releases/tag/0.13.0))
