### ISSUE TITLE
PyPi packages miss tests

### ISSUE THREAD

**Issue by 02strich** [jacksmith15/statham-schema#83]
**Describe the bug**
The pypi package currently has a broken tests folder that misses most of the unit test files. This stops me from running those tests against my local setup.

**Steps to Reproduce**
Download the latest release from pypi and check the contents of the src distribution

**Expected behaviour**
The distribution either has no test data or working one

**Actual behaviour**
Trying to run tests fails but the system still gets polluted with partial test files

**System information**
- Python version: 3.7

**Workaround**
n/a

**Additional context**

**Comment by jacksmith15** [comment]
Thanks for reporting! No tests should be included in the packaged project - I shall fix the `setup.py` to remove them.

If you want to run tests - I recommend following the instructions [here](https://github.com/jacksmith15/statham-schema#development).

**Comment by jacksmith15** [comment]
I've released `0.13.2` which stops polluting site-packages with `tests/`.
