### ISSUE TITLE
Update requirements typing_extensions~=3.7 to a new version

### ISSUE THREAD

**Issue by tanzim-bgl** [jacksmith15/statham-schema#90]
**Description of requested feature**

I would like to use this with other libraries, such as dataclasses_avroschema. However there is an overlap where the dependencies are newer within that library. I would like this to be updated if possible.

**Workaround**

I am using pip install --no-deps to get passed this but would like to avoid it in the future.

**Comment by jacksmith15** [comment]
Version 0.14.0 now released, and will work with typing extensions <5.0.0

Thanks for the PR @tanzim-bgl
